language: node_js

node_js:
  - "12.16.1"

services:
  - redis

cache:
  npm: true
  directories:
    - ~/.cache
    - ~/.nvm
    - ~/.npm

install:
  - npm install

script:
  - npm test

notifications:
  email: false
